"""Pydantic models shared across the application."""

from pydantic import BaseModel, Field


# ---------- LLM structured-output schemas ----------

class StockInfo(BaseModel):
    """Structured data the LLM extracts from a collect conversation."""
    stock_name: str = Field(description="Name or ticker of the stock, e.g. TCS, RELIANCE")
    sector: str = Field(description="Sector the stock belongs to, e.g. IT, Banking")
    linked_stocks: list[str] = Field(
        default_factory=list,
        description="Other stock names that are related/linked to this stock",
    )


class CypherOutput(BaseModel):
    """Structured output: a Cypher query generated by the LLM."""
    cypher_query: str = Field(description="A valid Neo4j Cypher query to answer the user's question")


# ---------- API request / response schemas ----------

class CollectRequest(BaseModel):
    user_message: str = Field(description="The user's current message in the collection conversation")
    session_id: str = Field(
        default="default",
        description="Session identifier to maintain multi-turn conversation state",
    )


class CollectResponse(BaseModel):
    assistant_message: str = Field(description="The assistant's reply to the user")
    extracted: StockInfo | None = Field(
        default=None,
        description="Extracted stock info (populated only when all fields collected)",
    )
    stored: bool = Field(default=False, description="Whether the data was persisted to Neo4j")


class QueryRequest(BaseModel):
    question: str = Field(description="Natural-language question about stocks")


class QueryResponse(BaseModel):
    answer: str = Field(description="Natural-language answer derived from graph data")
    cypher_used: str = Field(default="", description="The Cypher query that was executed")
